### ISSUE TITLE
Loading css chunk failed on Arch Linux for v0.8.13

### ISSUE THREAD

**Issue by y-not-u** [umijs/mako#1609] opened 2024-09-24 08:24 UTC
It was normal on v0.8.12, but it's not working on v0.8.13

**Comment by stormslowly** [comment] 2024-09-25 03:48
if the http error code is 504 , it will be fixed by https://github.com/umijs/mako/pull/1612

**Comment by y-not-u** [comment] 2024-09-25 06:37
> if the http error code is 504 , it will be fixed by #1612

After I updated to v0.8.14, the `async.css` still responded 504.

**Comment by stormslowly** [comment] 2024-09-25 07:45
@y-not-u  could plz help to investigate in Arch Linux ，the root cause is  express-http-proxy request to mako hyper server with keep alive, but hyper is config to disable keep alive. 

could plz try to do some modify in node_module to verify keep alive is disable or not.

btw:  do you update @umijs/bundler-mako to 0.8.14 ?

**Comment by y-not-u** [comment] 2024-09-25 08:26
@stormslowly I didn't install `@umijs/bundler-mako`, but I found it has been installed by other package. And the version is 0.8.13. 
I don't know how to update `@umijs/bunder-mako`. Even though I installed version 0.8.14 manually, it still didn't work.

I'm glad to help you to find the issue.

**Comment by stormslowly** [comment] 2024-09-25 09:42
if you are using umi,   you can verify it easily  by change version to 4.0.0-canary.20240925.1

**Comment by y-not-u** [comment] 2024-09-26 01:19
after executing the cmd, the output is as follows: 
`node_modules/.pnpm/@umijs+bundler-mako@0.8.13/node_modules/@umijs/bundler-mako`.

And then I patch the index.js file, it works! 
the only question is I updated `@umijs/mako` to `^0.8.14` but `bundler-mako` is still `0.8.13`

**Comment by stormslowly** [comment] 2024-09-26 09:43
you  can 
```bash
npm ls @umijs/bundler-mako 
```
to inspect who introduced it

**Closed by stormslowly** 2024-09-26 09:43 UTC
